### ISSUE TITLE
Local database issues

### ISSUE THREAD

**Issue by bdsinger** [langcog/childesr#37]
Hi, while attempting to help with the other issue about get_context speed, I downloaded the mysql file available from http://childes-db.stanford.edu/releases.html and got a local mysql server set up with it.

In doing so I discovered two issues, which unfortunately prevent the local database solution from being a viable alternative:

1) The local database contains only English collections ("Eng-NA" and "Eng-UK") although this is not mentioned on the releases page. [Edit: am moving this to the childes-db repo issue page]

2) The function get_context() fails if a collection is specified:
             could not run statement: Unknown column 'collection_name' in 'where clause'

This doesn't happen when using the remote default mysql server, just when a local connection is supplied. I see that the collection table's name is renamed to collection_name here, but haven't followed the logic through yet, perhaps will get time soon to debug myself and will post a fix if so.

**Comment by smeylan** [comment]
This sounds like we have a legacy file up on the releases page — if you look at the JSON that childesr downloads to determine the most recent version (http://childes-db.stanford.edu/childes-db.json), you can see that it is looking for a version "2018.1". I suspect because of the change in the column names (`collection_name`) that we are hosting the wrong one. @amsan7, did you do the semantically-versioned S3 one? Can you update that with the one used by the EC2 instance?

**Comment by bdsinger** [comment]
Yes it is working after I ingested the 0.1.2 version of the database! So I guess these 2 issues are really 1. Which is solved with the newer database, making it 0 issues when using the local database. In fact, the other issue about get_context goes away as well with a local 0.1.2 database, since on my laptop the call is about 5 seconds or so.

**Comment by mcfrank** [comment]
Oh wow, glad that cleared things up!

**Comment by smeylan** [comment]
@bdsinger did you just get the 0.1.2 by URL hacking the S3 address? Or do we link to it somewhere? I'll add the newer one to the releases page and switch the site over to year-based versions rather than semantic versions.
