### ISSUE TITLE
can one get_tokens from corpora in phonbank?

### ISSUE THREAD

**Issue by alecristia** [langcog/childesr#41]
For example, `get_tokens(collection="French",token="chien")` returns the 10 corpora inside French in childes proper:
Champaud     Geneva Hammelrath   Hunkeler   Leveille       MTLN    Palasis    Pauline 
  VionColas       York 
 
But not the French corpora hosted in phonbank (though notice Hunkeler is present in both):

Corpus | Age Range | N | Comments
-- | -- | -- | --
GoadRose | 1;0-4;0 | 2 | Québécois French
Hunkeler | 1;6-2;6 | 2 | linked to video
Kern-French | 0;7-2;01 | 4 |  
Lyon | 1;0-3;0 | 5 | includes MOR analysis
Paris | 0;7-6;03 | 6 | includes MOR analysis
Stanford-French | 0;9-1;07 | 6 |  
Yamaguchi | 1;11-4;03 | 1 | includes MOR analysis

**Comment by smeylan** [comment]
For the 2018 release: if a corpus is in phonbank but not CHILDES, then it isn't in childes-db. However, the next release we are trying to add any that conform to the CHILDES format, and add quick access to the transcriptions. I have a personal interest in this because the Providence corpus—which is my go-to corpus—has been moved to Phonbank exclusively for English-NA, so this should happen by January or February 2020

**Comment by alecristia** [comment]
Wonderful, thanks! I'll keep an eye out for it.

**Comment by smeylan** [comment]
@alecristia Phonbank datasets are now present in the childes-db 2020.1 version!
